---
description: this is a repository to hold book store configuration

eureka:
  client:
    serviceUrl:
      defaultZone: "http://registryserver:9011/eureka"
      

bookstore:
  discountPercentage: 12