spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rmalired/microservices
          search-paths:
          - config
server:
  port: 9001

management:
  security:
    enabled: false        